source 'https://rubygems.org'

gem 'middleman', '4.4.2'
gem 'middleman-dato', '0.10.0'
gem 'dato', '0.8.1'
gem 'haml', '5.2.2'
gem 'middleman-paginate'
gem 'middleman-livereload'
gem 'middleman-search_engine_sitemap'
gem 'middleman-minify-html'
gem 'slim'
# gem 'middleman-svg'
# gem 'pry'
